# Generated by Django 4.2.2 on 2023-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_total_expense_alter_budget_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('taken_date', models.DateField()),
                ('status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=200)),
            ],
        ),
    ]
