# Generated by Django 4.2.2 on 2023-06-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='source',
            new_name='taken_from',
        ),
    ]
