# Generated by Django 4.2.2 on 2023-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_source_debt_taken_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_no', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('total_income', models.CharField(default=None, max_length=50)),
                ('term', models.DateField()),
            ],
        ),
    ]
