# Generated by Django 4.2.2 on 2023-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_income_income_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='term',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=200),
        ),
    ]
